version: '3.5'

services:
  db:
    build: ./.mongo/
    image: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  server:
    build: .
    depends_on:
      - db
    ports: 
      - 4000:4000
    volumes:
      - .:/opt/app
volumes:
  mongodb: